In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.2.2


In [3]:
s = pd.Series([1,2,3,4,5,6,7])
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [4]:
s[1]

2

In [5]:
data = {
    "name" :["Sep", "Ali", "Mobin"],
    "age" : [25,40,56],
    "city": ["Teh", "NYC", "Paris"]
}
df = pd.DataFrame(data)
df

name  age   city
0    Sep   25    Teh
1    Ali   40    NYC
2  Mobin   56  Paris

In [6]:
df["name"]

0      Sep
1      Ali
2    Mobin
Name: name, dtype: object

In [7]:
df.iloc[2] #Access Row

name    Mobin
age        56
city    Paris
Name: 2, dtype: object

In [8]:
df["city"].dtype

dtype('O')

In [9]:
df["name"] = df["name"].astype("str")

In [10]:
df["name"].dtype

dtype('O')

In [11]:
data = [1,2,3,4]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
dtype: int64

In [13]:
import numpy as np

In [14]:
data = np.array([1,2,3,4])
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
dtype: int64

In [15]:
data = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
series = pd.Series(data)
series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [16]:
data = [1,2,3,4]
index = ["a", "b", "c", "d",]
series = pd.Series(data, index = index)
series

a    1
b    2
c    3
d    4
dtype: int64

In [17]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index, name='example', dtype='float64')
series

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: example, dtype: float64

In [20]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
series.dtype

dtype('int64')

In [21]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
series.shape

(5,)

In [22]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)
series.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [23]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
series.values

array([1, 2, 3, 4, 5])

In [24]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
series.size

5

In [26]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)
series.values

array([1, 2, 3, 4, 5])

In [28]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [30]:
series + 2 #can do verctorized operations

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [31]:
series * 3

0     3
1     6
2     9
3    12
4    15
dtype: int64

In [32]:
series ** 2

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [33]:
np.sin(series)

0    0.841471
1    0.909297
2    0.141120
3   -0.756802
4   -0.958924
dtype: float64

In [35]:
np.log(series)

0    0.000000
1    0.693147
2    1.098612
3    1.386294
4    1.609438
dtype: float64

In [36]:
series > 3

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [37]:
series == 4

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [39]:
series1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
series2 = pd.Series([4, 5, 6], index=['b', 'c', 'd'])

series1 + series2 #operations are done basd on lables rather than position

a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64

In [41]:
series1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
series2 = pd.Series([4, 5, 6], index=['b', 'c', 'a'])

series1 + series2 

a    7
b    6
c    8
dtype: int64

In [43]:
series1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
series2 = pd.Series([4, 5, 6], index=['b', 'c', 'd'])

series1 + series2 
# abels that are present in one Series but not the other, the result will be marked as missing (NaN).

a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64

In [44]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
series = pd.Series(data)

series.head()  # First 5 elements

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [45]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
series = pd.Series(data)

series.head(3)  # First 3 elements

0    1
1    2
2    3
dtype: int64

In [46]:
series.tail(3)  # Last 3 elements

7     8
8     9
9    10
dtype: int64

In [48]:
data = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
series = pd.Series(data)

series.unique() #unique(): Returning Unique Values in a Series

array([1, 2, 3, 4])

In [51]:
data = [1, 2, 2, 3, 3,4, 4, 4, 4, 4]
series = pd.Series(data)

series.value_counts() #value_counts(): Counting Occurrences of Unique Values

4    5
2    2
3    2
1    1
Name: count, dtype: int64

In [53]:
data = [4, 2, 8, 1, 9, 5]
series = pd.Series(data)

series.sort_values() #sort_values(): Sorting a Series by Values

3    1
1    2
0    4
5    5
2    8
4    9
dtype: int64

In [54]:
series.sort_values(ascending=False)

4    9
2    8
5    5
0    4
1    2
3    1
dtype: int64

In [55]:
series.sort_values(ascending=True)

3    1
1    2
0    4
5    5
2    8
4    9
dtype: int64

In [57]:
data = [4, 2, 8, 1, 9, 5]
index = ['b', 'd', 'a', 'e', 'c', 'f']
series = pd.Series(data, index=index)

series.sort_index() #sort_index(): Sorting a Series by Index

a    8
b    4
c    9
d    2
e    1
f    5
dtype: int64

In [59]:
s = pd.Series(['1', '2', '3', '4', '5'])
s.dtype

dtype('O')

In [60]:
# Convert to integer
s_int = s.astype(int)
s_int.dtype

dtype('int64')

In [62]:
s_float = s.astype(float)
s_float.dtype

dtype('float64')

In [63]:
s_mixed = pd.Series([1, 2.5, 3, 4.7, 5])
s_mixed.dtype

dtype('float64')

In [64]:
s_mixed.astype(int)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [65]:
s_mixed.astype(float)

0    1.0
1    2.5
2    3.0
3    4.7
4    5.0
dtype: float64

In [66]:
dates = pd.Series(['2023-01-01', '2023-02-15', '2023-03-30'])
dates

0    2023-01-01
1    2023-02-15
2    2023-03-30
dtype: object

In [68]:
dates_dt = pd.to_datetime(dates)
dates_dt.dtype

dtype('<M8[ns]')

In [69]:
# Handling different date formats
mixed_dates = pd.Series(['2023-01-01', '15/02/2023', 'March 30, 2023'])
pd.to_datetime(mixed_dates, format='mixed')

0   2023-01-01
1   2023-02-15
2   2023-03-30
dtype: datetime64[ns]

In [70]:
colors = pd.Series(['red', 'blue', 'green', 'red', 'blue', 'red', 'green'])
colors

0      red
1     blue
2    green
3      red
4     blue
5      red
6    green
dtype: object

In [71]:
colors_cat = colors.astype('category')
colors_cat.dtype

CategoricalDtype(categories=['blue', 'green', 'red'], ordered=False, categories_dtype=object)

In [74]:
colors_cat.cat.categories #NAFAHMIDAM

Index(['blue', 'green', 'red'], dtype='object')

In [75]:
# Get category codes
colors_cat.cat.codes

0    2
1    0
2    1
3    2
4    0
5    2
6    1
dtype: int8

In [76]:
s_with_error = pd.Series(['1', '2', '3', 'four', '5'])
s_with_error

0       1
1       2
2       3
3    four
4       5
dtype: object

In [77]:
s_with_error.astype(int)

ValueError: invalid literal for int() with base 10: 'four'

In [79]:
s_with_error.astype(int, errors="ignore")

0       1
1       2
2       3
3    four
4       5
dtype: object